sequenceDiagram
    participant usuario
    participant browser
    participant server

    usuario->>browser: El usuario introduce la URL en el navegador y presiona Enter 

    Note right of browser:El navegador envía la petición al servidor.
    browser->>server: HTTP GET https://studies.cs.helsinki.fi/exampleapp/spa
    activate server
    server-->>browser: HTML-code
    deactivate server

    browser->>server: HTTP GET https://studies.cs.helsinki.fi/exampleapp/main.css
    activate server
    server-->>browser: main.css
    deactivate server

    browser->>server: HTTP GET https://studies.cs.helsinki.fi/exampleapp/spa.js
    activate server
    server-->>browser: spa.js
    deactivate server

    Note right of browser: spa.js se ejecuta y solicita los datos de notas

    browser->>server: HTTP GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate server
    server-->>browser: data.js
    deactivate server

    Note right of browser: El navegador renderiza la lista de notas

    browser->>usuario: El usuario visualiza la página con la lista de notas cargada 
    